import { ClaimFormType } from "@/schema";
import { TreatmentType } from "@/types/claimType";
import { CurrencyUnit, PaymentMethod } from "@/types/paymentType";

const INITIAL_FORM_DATA: ClaimFormType = {
  act: 1,
  id: "00000000-0000-0000-0000-000000000000",
  version: 0,
  memberId: "",
  memberHistId: "",
  branchMainId: "",
  branchHandlerId: "",
  requestorId: "",
  memberBenificialId: "",
  beneficiaryId: "",
  memberCode: "",
  policyNo: "",
  memberName: "",
  citizenIdentity: "",
  policyHolder: "",
  relationship: "",
  beneficialRelationship: "",
  updateBenenfit: 0,
  beneficiaryCitizenIdentity: "",
  dob: "",
  effectiveFrom: "",
  effectiveTo: "",
  createdBy: "",
  updatedBy: "",
  contactEmail: "",
  contactPhone: "",
  email: "",
  phoneNumber: "",
  medicalFacilities: "",
  treatmentType: TreatmentType.INPATIENT,
  treatmentDate: new Date(""),
  dischargeDate: new Date(),
  eventDate: new Date(""),
  claimCost: 0,
  diagnosis: "",
  paymentMethod: PaymentMethod.CREDIT_TRANSFER,
  currencyUnit: CurrencyUnit.VND,
  bankName: "",
  bankAccountNumber: "",
  documents: [],
  fileOther: [],
  fileInvoice: [],
  memberBenificialName: "",
};

export default INITIAL_FORM_DATA;
